-- MySQL Script generated by MySQL Workbench
-- Thu Apr 30 11:16:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Worker` (
  `Worker_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Worker_id`),
  UNIQUE INDEX `Worker_id_UNIQUE` (`Worker_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glasses` (
  `glasses_id` INT NOT NULL AUTO_INCREMENT,
  `colour_mont` VARCHAR(45) NULL,
  `colour_glass` VARCHAR(45) NULL,
  `montura` ENUM('flotant', 'pasta', 'metallica') NOT NULL DEFAULT 'flotant',
  `price` DECIMAL(20) NULL,
  PRIMARY KEY (`glasses_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `Client_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `direction` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Phone` VARCHAR(45) NULL,
  `Client_Client_id` INT NOT NULL,
  PRIMARY KEY (`Client_id`, `Client_Client_id`),
  INDEX `fk_Client_Client2_idx` (`Client_Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Client2`
    FOREIGN KEY (`Client_Client_id`)
    REFERENCES `mydb`.`Client` (`Client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `Factura_id` INT NOT NULL AUTO_INCREMENT,
  `Worker_Worker_id` INT NOT NULL,
  `Client_Client_id` INT NOT NULL,
  `Glasses_glasses_id` INT NOT NULL,
  `price` DECIMAL(45) NULL,
  PRIMARY KEY (`Factura_id`, `Worker_Worker_id`, `Client_Client_id`, `Glasses_glasses_id`),
  INDEX `fk_Factura_Worker1_idx` (`Worker_Worker_id` ASC) VISIBLE,
  INDEX `fk_Factura_Client1_idx` (`Client_Client_id` ASC) VISIBLE,
  INDEX `fk_Factura_Glasses1_idx` (`Glasses_glasses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Worker1`
    FOREIGN KEY (`Worker_Worker_id`)
    REFERENCES `mydb`.`Worker` (`Worker_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Factura_Client1`
    FOREIGN KEY (`Client_Client_id`)
    REFERENCES `mydb`.`Client` (`Client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Factura_Glasses1`
    FOREIGN KEY (`Glasses_glasses_id`)
    REFERENCES `mydb`.`Glasses` (`glasses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `Supplier_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Direction` VARCHAR(45) NULL,
  `Town` VARCHAR(45) NULL,
  `Index` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Tel` VARCHAR(45) NULL,
  `Fax` VARCHAR(45) NULL,
  `Nif` VARCHAR(45) NULL,
  PRIMARY KEY (`Supplier_id`),
  UNIQUE INDEX `Supplier_id_UNIQUE` (`Supplier_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `Brand_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Supplier_Supplier_id1` INT NOT NULL,
  `Glasses_glasses_id` INT NOT NULL,
  PRIMARY KEY (`Brand_id`, `Supplier_Supplier_id1`, `Glasses_glasses_id`),
  UNIQUE INDEX `Brand_id_UNIQUE` (`Brand_id` ASC) VISIBLE,
  INDEX `fk_Brand_Supplier2_idx` (`Supplier_Supplier_id1` ASC) VISIBLE,
  INDEX `fk_Brand_Glasses1_idx` (`Glasses_glasses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Supplier2`
    FOREIGN KEY (`Supplier_Supplier_id1`)
    REFERENCES `mydb`.`Supplier` (`Supplier_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Brand_Glasses1`
    FOREIGN KEY (`Glasses_glasses_id`)
    REFERENCES `mydb`.`Glasses` (`glasses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
